### ISSUE TITLE
Abandonware?

### ISSUE THREAD

**Issue by watchwood** [tippingmedia/venti#1]
Is this repo abandonware, or are you actively developing it?  The readme is a touch vague on that.

**Comment by a-am** [comment]
We are in active development however our development may be sporadic since our main client projects must come first.  We have also made this open source so that community can be apart of shaping this plugin.

**Comment by felixdenoix** [comment]
Hi !
Is there a beginning of documentation in order to start using the plugin ? ( and possibly start contributing 😀)
Thanks in advance

**Comment by a-am** [comment]
@felixdenoix we have not started documentation at this point.  We have had to focus on client work lately. However most of the functionality is the same as  Venti 2 except for the params eid & cid.  Those are no longer present since we are not generating an row in the database for each recurrence.

**Comment by felixdenoix** [comment]
Nice !
Thanks for the quick reply,
I'll start using the plugin with the 2.X doc then
